//! SAP HANA 驱动：基于 `hdbconnect`（纯 Rust 协议实现）。
//!
//! 连接串与 XCode 兼容：
//!
//! ```text
//! Server=hana.local;Port=30015;Uid=SYSTEM;Pwd=***;provider=hana
//! ```
//!
//! 实现要点：
//! - 自增：`GENERATED BY DEFAULT AS IDENTITY`，插入后读 `SELECT CURRENT_IDENTITY_VALUE() FROM DUMMY` 回写
//! - 参数：hdbconnect 的参数编码依赖 serde 类型推导，这里统一采用**字面量内联**
//!   （值来自 [`DbValue`]，按标准 SQL 转义），避免为动态值构造序列化器
//! - 类型：BOOLEAN/TINYINT/SMALLINT/INTEGER/BIGINT/REAL/DOUBLE/DECIMAL/NVARCHAR/NCLOB/
//!   TIMESTAMP/VARBINARY/BLOB（见方言）
//! - 分页 `LIMIT n OFFSET m`
//! - 事务：`begin` 关闭自动提交，`commit/rollback` 结束事务后恢复自动提交
//!
//! 已知限制：写入受影响行数由 hdbconnect 高层 API 不直接提供，统一返回 0。

use hdbconnect::{Connection as HanaConnection, HdbValue, Row as HanaRow};

use crate::dal::ConnectionString;
use crate::dialect::DatabaseKind;
use crate::error::{Error, Result};
use crate::http::{LiteralStyle, inline_params};
use crate::session::{RowSet, SqlSession};
use crate::value::DbValue;

/// HANA 会话。
pub struct HanaSession {
    /// hdbconnect 连接
    conn: HanaConnection,
}

/// 连接设置。
#[derive(Debug, Clone, PartialEq)]
struct HanaSettings {
    /// 主机
    host: String,
    /// 端口（默认 30015，SAP HANA 实例 00 的 SQL 端口）
    port: u16,
    /// 用户名（默认 SYSTEM）
    user: String,
    /// 密码
    password: String,
}

impl HanaSession {
    /// 根据 XCode 风格连接串打开连接。
    pub fn open(conn_str: &ConnectionString) -> Result<Self> {
        let settings = parse_settings(conn_str)?;
        let url = format!(
            "hdb://{}:{}@{}:{}",
            settings.user, settings.password, settings.host, settings.port
        );
        let conn = HanaConnection::new(url.as_str()).map_err(|e| {
            Error::Db(format!(
                "连接 HANA 失败（{}:{}）：{e}",
                settings.host, settings.port
            ))
        })?;
        Ok(Self { conn })
    }
}

/// 解析连接串（与 XCode 键名兼容）。
fn parse_settings(cs: &ConnectionString) -> Result<HanaSettings> {
    let host = cs
        .get("server")
        .or(cs.get("host"))
        .or(cs.get("data source"))
        .unwrap_or("127.0.0.1")
        .to_string();
    let port = match cs.get("port") {
        Some(v) => v
            .parse::<u16>()
            .map_err(|e| Error::Model(format!("无效的 Port \"{v}\"：{e}")))?,
        None => 30015,
    };
    let user = cs
        .get("uid")
        .or(cs.get("user"))
        .or(cs.get("username"))
        .unwrap_or("SYSTEM")
        .to_string();
    let password = cs
        .get("pwd")
        .or(cs.get("password"))
        .or(cs.get("passwd"))
        .unwrap_or("")
        .to_string();
    Ok(HanaSettings {
        host,
        port,
        user,
        password,
    })
}

/// HdbValue → `DbValue`。
fn hana_to_dbvalue(value: &HdbValue) -> DbValue {
    match value {
        HdbValue::NULL => DbValue::Null,
        HdbValue::BOOLEAN(v) => DbValue::Bool(*v),
        HdbValue::TINYINT(v) => DbValue::Int(i64::from(*v)),
        HdbValue::SMALLINT(v) => DbValue::Int(i64::from(*v)),
        HdbValue::INT(v) => DbValue::Int(i64::from(*v)),
        HdbValue::BIGINT(v) => DbValue::Int(*v),
        HdbValue::REAL(v) => DbValue::Float(f64::from(*v)),
        HdbValue::DOUBLE(v) => DbValue::Float(*v),
        // DECIMAL 以文本保持精度
        HdbValue::DECIMAL(v) => v
            .to_string()
            .parse::<rust_decimal::Decimal>()
            .map(DbValue::Decimal)
            .unwrap_or_else(|_| DbValue::Text(v.to_string())),
        HdbValue::STRING(v) => DbValue::Text(v.clone()),
        HdbValue::STR(v) => DbValue::Text(v.to_string()),
        HdbValue::BINARY(v) => DbValue::Blob(v.clone()),
        // 其它类型（时间/大对象/空间类型等）按 Debug 文本保留，不丢数据
        other => DbValue::Text(format!("{other:?}")),
    }
}

/// 驱动错误 → 统一错误。
fn map_err(e: hdbconnect::HdbError) -> Error {
    Error::Db(format!("HANA 错误：{e}"))
}

impl SqlSession for HanaSession {
    fn kind(&self) -> DatabaseKind {
        DatabaseKind::Hana
    }

    fn execute(&mut self, sql: &str, params: &[DbValue]) -> Result<u64> {
        let sql = inline_params(sql, params, LiteralStyle::Standard)?;
        self.conn.exec(&sql).map_err(map_err)?;
        // hdbconnect 高层 API 不返回受影响行数
        Ok(0)
    }

    fn query(&mut self, sql: &str, params: &[DbValue]) -> Result<RowSet> {
        let sql = inline_params(sql, params, LiteralStyle::Standard)?;
        let result_set = self.conn.query(&sql).map_err(map_err)?;

        // 列名（HANA 的 ResultSet 元数据提供字段名）
        let columns: Vec<String> = result_set
            .metadata()
            .iter()
            .map(|field| field.columnname().to_string())
            .collect();
        let mut set = RowSet::new(columns);

        for row in result_set {
            let mut row: HanaRow = row.map_err(map_err)?;
            let mut values = Vec::new();
            while let Some(value) = row.next_value() {
                values.push(hana_to_dbvalue(&value));
            }
            set.push(values);
        }
        Ok(set)
    }

    fn begin(&mut self) -> Result<()> {
        self.conn.set_auto_commit(false).map_err(map_err)
    }

    fn commit(&mut self) -> Result<()> {
        self.conn.commit().map_err(map_err)?;
        self.conn.set_auto_commit(true).map_err(map_err)
    }

    fn rollback(&mut self) -> Result<()> {
        self.conn.rollback().map_err(map_err)?;
        self.conn.set_auto_commit(true).map_err(map_err)
    }

    fn last_identity(&mut self) -> Result<i64> {
        self.last_identity_of("")
    }

    fn last_identity_of(&mut self, _table: &str) -> Result<i64> {
        // HANA 的会话级自增值
        let set = self.query("SELECT CURRENT_IDENTITY_VALUE() FROM DUMMY", &[])?;
        Ok(set
            .first()
            .and_then(|row| row.get(0))
            .and_then(DbValue::as_i64)
            .unwrap_or(0))
    }

    fn table_exists(&mut self, table: &str) -> Result<bool> {
        let set = self.query(
            "SELECT COUNT(*) FROM SYS.TABLES WHERE SCHEMA_NAME = CURRENT_SCHEMA AND TABLE_NAME = ?",
            &[DbValue::Text(table.to_string())],
        )?;
        Ok(set
            .first()
            .and_then(|row| row.get(0))
            .and_then(DbValue::as_i64)
            .unwrap_or(0)
            > 0)
    }

    fn table_columns(&mut self, table: &str) -> Result<Vec<String>> {
        let set = self.query(
            "SELECT COLUMN_NAME FROM SYS.TABLE_COLUMNS \
             WHERE SCHEMA_NAME = CURRENT_SCHEMA AND TABLE_NAME = ? ORDER BY POSITION",
            &[DbValue::Text(table.to_string())],
        )?;
        Ok(set
            .rows
            .iter()
            .filter_map(|row| row.get(0).map(DbValue::to_text))
            .collect())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn settings_parsing() {
        let cs = ConnectionString::parse(
            "Server=hana.local;Port=30041;Uid=SYSTEM;Pwd=***;provider=hana",
        );
        let s = parse_settings(&cs).unwrap();
        assert_eq!(s.host, "hana.local");
        assert_eq!(s.port, 30041);
        assert_eq!(s.user, "SYSTEM");

        let cs = ConnectionString::parse("provider=sap");
        let s = parse_settings(&cs).unwrap();
        assert_eq!(s.port, 30015);
        assert_eq!(s.user, "SYSTEM");
    }

    #[test]
    fn value_mapping() {
        assert!(matches!(hana_to_dbvalue(&HdbValue::NULL), DbValue::Null));
        assert_eq!(hana_to_dbvalue(&HdbValue::INT(3)), DbValue::Int(3));
        assert_eq!(
            hana_to_dbvalue(&HdbValue::STRING("A-001".into())),
            DbValue::Text("A-001".into())
        );
        assert_eq!(
            hana_to_dbvalue(&HdbValue::STRING("12.50".into())),
            DbValue::Text("12.50".into())
        );
        assert!(hana_to_dbvalue(&HdbValue::STRING("2026-09-27 10:30:00".into()))
            .as_datetime()
            .is_some());
    }
}
